# Generated by Django 5.1.1 on 2024-09-27 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0003_report_image_report_status_alter_report_report_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='public_user',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='report_id',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='public_user',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
