# Generated by Django 5.1.1 on 2024-09-28 22:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0008_public_user_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Found', 'Found'), ('Closed', 'Closed')], default='Pending', max_length=50),
        ),
        migrations.CreateModel(
            name='ReportMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('additional_data', models.JSONField(default=dict)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match', to='surveillance.report')),
            ],
        ),
    ]
